spring:
  application:
    name : LLMService
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/test_xeat
    username: hurray
    password: rlaalstj1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #?? ?? DB
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true #???? ? ??? ????
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true #??? ????.
    defer-datasource-initialization: true # ?????? ?? data.sql ??!!
chat-GPT:
  api-key: "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"
  base-url: "https://api.openai.com/v1"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.16.211.57:19090/eureka/